// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddFilesInput = { projectId: string, paths: Array<string>, };

export type AiBudget = { contextTokens: number, maxOutputTokens: number, maxImagesPerRequest: number, rerank: boolean, concurrency: number, warnAboveTokens: number | null, };

export type AiProfile = { id: string, name: string, baseUrl: string, protocol: ApiProtocol,
/**
 * The API key is never returned — only whether one is stored.
 */
hasKey: boolean, defaultModel: string | null, supportsVision: boolean, supportsTools: boolean, supportsEmbed: boolean, jsonSchema: boolean, extraHeaders: Record<string, string>, timeoutMs: number, createdAt: string, lastOkAt: string | null, };

export type AiProfileInput = { id: string | null, name: string, baseUrl: string, protocol: ApiProtocol,
/**
 * Present only when the user typed or changed it. `""` clears the key.
 */
apiKey: string | null, defaultModel: string | null, extraHeaders: Record<string, string> | null, timeoutMs: number | null, };

/**
 * Wire protocol used by an AI connection. Both variants are implemented
 * directly on reqwest; no vendor SDK is linked into the app.
 */
export type ApiProtocol = "openai" | "anthropic";

export type AppError = { code: string, message: string, i18nKey: string, details: unknown | null, retriable: boolean, };

export type AppInfo = { version: string, buildDate: string, dataDir: string, license: string, };

/**
 * A file produced in `workspace/` by a Studio tool call (FR-T7). Survives the
 * tab that made it (AC-6-10).
 */
export type Artifact = { id: string, threadId: string | null, relPath: string, bytes: number, mime: string | null, importedSourceId: string | null, createdAt: string, };

export type AskInput = { projectId: string, threadId: string, text: string, scope: Scope, };

export type ChatMessage = { id: string, role: string, content: string, citations: Citation[], model: string | null, status: string, createdAt: string, 
/**
 * Present on a Studio assistant turn that proposed tool calls (P6). Shape is
 * `{ id, name, arguments }[]`; `unknown` here because MCP tool calls (P7)
 * may extend it. `null` for every Live Illustrator message.
 */
toolCalls: { id: string; name: string; arguments: unknown }[] | null, };

export type Citation = { sourceId: string, sourceName: string, documentId: string | null, chunkId: string | null, locator: unknown, quote: string | null, };

export type CommandOutput = { stdout: string, stderr: string, exitCode: number | null, timedOut: boolean, 
/**
 * One or both streams hit [`MAX_OUTPUT_BYTES`] and were cut.
 */
truncated: boolean, };

export type CreateProjectInput = { name: string, description: string | null, color: ProjectColor | null, };

export type DetailLevel = "simple" | "standard" | "detailed";

export type DiskCheck = { ok: boolean, neededBytes: number, freeBytes: number, };

/**
 * One page/slide/segment/sheet/section returned by `source_get_document`.
 */
export type DocumentPayload = { sourceId: string, ordinal: number, total: number, kind: string, title: string | null, text: string, 
/**
 * `wakaru-asset://` URL for the page image, when one exists.
 */
imageUrl: string | null, locator: unknown, };

/**
 * A page / slide / segment / sheet / section — the citation unit (docs/03 §2 GLOSSARY).
 * Returned by `source_get_document` (wired in Phase 2).
 */
export type DocumentUnit = { id: string, sourceId: string, ordinal: number, kind: string, title: string | null, text: string, imageRel: string | null, locator: unknown, };

export type ExportEstimate = { projectId: string, bytesWithoutEmbeddings: bigint, bytesWithEmbeddings: bigint, };

export type ExportInput = { ids: Array<string>, destDir: string, includeEmbeddings: boolean, };

export type ExportResult = { files: Array<string>, };

export type General = { 
/**
 * "home" | "last_project"
 */
startupView: string, checkUpdatesOnStart: boolean, };

export type GenerateInput = { projectId: string, sourceId: string, locator: unknown, level: DetailLevel, force: boolean, };

export type GenerateStarted = { 
/**
 * Set when generation started streaming; deltas arrive on `stream://*`.
 */
streamId: string | null, 
/**
 * Set when the answer came straight from the cache (no AI call).
 */
cached: Illustration | null, };

/**
 * The saved page explanation (docs/03 §4 `illustrations`).
 */
export type Illustration = { content: string, citations: Citation[], level: DetailLevel, model: string, createdAt: string, 
/**
 * true when this came from the cache (docs/06 §5.2 — "保存された解説").
 */
cached: boolean, };

export type IllustratorSettings = { enabled: boolean, 
/**
 * "simple" | "standard" | "detailed"
 */
defaultLevel: string, 
/**
 * "page" | "source" | "project"
 */
defaultScope: string, prefetchNext: boolean, carryOverPreviousPage: boolean, };

export type ImagesToPdfInput = { images: Array<string>, 
/**
 * "a4" | "a3" | "letter" | "fit"
 */
pageSize: string, 
/**
 * "auto" | "portrait" | "landscape"
 */
orientation: string, 
/**
 * "none" | "sm" | "md" | "lg"
 */
margin: string, 
/**
 * "contain" | "cover"
 */
fit: string, destPath: string, };

export type ImportToStudioInput = { projectId: string, threadId: string, 
/**
 * "new_tab" | "append"
 */
mode: string, targetTabId: string | null, };

export type IngestSettings = { concurrency: number, fetchWebImages: boolean, allowPrivateNetwork: boolean, };

export type Job = { id: string, kind: JobKind, status: JobStatus, projectId: string | null, sourceId: string | null, phase: string | null, done: number, total: number, message: string | null, startedAt: string | null, endedAt: string | null, };

export type JobKind = "ingest" | "transcribe" | "embed" | "export" | "import";

/**
 * Payload of the `job://progress` event (docs/02 §5).
 */
export type JobProgress = { jobId: string, projectId: string | null, sourceId: string | null, kind: JobKind, phase: string, done: number, total: number, message: string | null, };

export type JobStatus = "queued" | "running" | "done" | "failed" | "cancelled";

export type Language = { 
/**
 * "en" | "ja" | "zh-Hans"
 */
ui: string, 
/**
 * "follow_ui" | "match_source" | "en" | "ja" | "zh-Hans"
 */
aiResponse: string, };

export type Locator = { "t": "page", page: number, bbox: [number, number, number, number] | null, } | { "t": "time", tStart: number, tEnd: number, speaker: string | null, } | { "t": "region", bbox: [number, number, number, number], } | { "t": "cell", sheet: string, range: string, } | { "t": "line", start: number, end: number, } | { "t": "path", pointer: string, } | { "t": "anchor", selector: string, char_start: number | null, char_end: number | null, } | { "t": "whole" };

export type McpConnectResult = { tools: Array<McpTool>, };

export type McpServer = { id: string, name: string, 
/**
 * `"stdio"` or MCP Streamable `"http"`.
 */
transport: string, command: string | null, args: Array<string>, url: string | null, 
/**
 * Names of env vars this server sets (values are not exposed — a value may
 * be a `keychain:<ref>`).
 */
envKeys: Array<string>, enabled: boolean, connected: boolean, lastError: string | null, };

export type McpTool = { serverId: string, serverName: string, 
/**
 * The tool's own name, as the server reports it.
 */
name: string, description: string | null, 
/**
 * `"<serverSlug>__<name>"` — what the model sees (docs/05 §6.3).
 */
qualifiedName: string, 
/**
 * `"ask"` | `"always_allow"` | `"deny"`.
 */
policy: string, };

export type McpUpsertInput = { id: string | null, name: string, transport: string, command: string | null, args: Array<string>, url: string | null, 
/**
 * `name -> value`. A value of `keychain:<ref>` is resolved from the OS
 * keychain at connect time; anything else is stored as-is.
 */
env: Record<string, string>, };

export type OpenTabInput = { projectId: string, sourceId: string, locator: unknown | null, };

export type Project = { id: string, name: string, description: string, color: ProjectColor, schemaVersion: string, createdAt: string, updatedAt: string, openedAt: string | null, archivedAt: string | null, sortOrder: number, };

/**
 * A stable colour slot for project cards (resolved to a token on the frontend).
 * Consumed by the projects service in Phase 1.
 */
export type ProjectColor = "accent-1" | "accent-2" | "accent-3" | "accent-4" | "accent-5";

/**
 * Lighter row for the home grid / sidebar (adds counts).
 */
export type ProjectSummary = { id: string, name: string, description: string, color: ProjectColor, archived: boolean, sourceCount: number, lastOpenedAt: string | null, updatedAt: string, };

/**
 * A model role (docs/03 §3 `model_roles`). `organizer` falls back to `chat`,
 * `embedding` falls back to local (Phase 3+: to "none / FTS only").
 */
export type Role = "chat" | "vision" | "embedding" | "organizer";

export type RoleBinding = { profileId: string, model: string, params: Record<string, unknown>, };

export type RoleBindings = { chat: RoleBinding | null, vision: RoleBinding | null, embedding: RoleBinding | null, organizer: RoleBinding | null, };

export type SandboxSettings = { commandTimeoutSec: number, autoAllowNewFileWrites: boolean, };

export type SaveTextInput = { content: string, destPath: string, 
/**
 * "md" | "txt"
 */
format: string, };

export type Scope = "page" | "source" | "project";

export type SearchHit = { projectId: string, projectName: string, sourceId: string, sourceName: string, documentId: string | null, ordinal: number | null, snippet: string, locator: unknown, };

export type SearchQuery = { scope: SearchScope, projectId: string | null, q: string, sourceId: string | null, limit: number, 
/**
 * "keyword" | "semantic" | "hybrid" (docs/06 §7). Ignored for global scope.
 */
mode: string | null, };

export type SearchResults = { hits: Array<SearchHit>, 
/**
 * true when a semantic component ran (vs. FTS-only fallback).
 */
semantic: boolean, };

export type SearchScope = "global" | "project";

export type Settings = { general: General, language: Language, illustrator: IllustratorSettings, ingest: IngestSettings, sandbox: SandboxSettings, transcription: Transcription, aiBudget: AiBudget, };

export type Source = { id: string, kind: SourceKind, originalName: string, url: string | null, mime: string | null, bytes: number, sha256: string | null, status: SourceStatus, errorCode: string | null, errorMessage: string | null, lang: string | null, pageCount: number | null, durationMs: number | null, summary: string | null, addedAt: string, analyzedAt: string | null, };

/**
 * Lightweight source detail for a preview header (name, kind, page count,
 * the reader-view asset URL for web links, etc.).
 */
export type SourceDetail = { id: string, kind: SourceKind, name: string, url: string | null, pageCount: number | null, status: SourceStatus, mime: string | null, bytes: bigint,
/**
 * `wakaru-asset://` URL to the primary rendered/original file, if any:
 * the normalised image, saved web reader markdown, or original imported
 * file. The URL is project-scoped and never exposes an absolute path.
 */
primaryAssetUrl: string | null, };

export type SourceKind = "pdf" | "slides" | "doc" | "image" | "audio" | "video" | "sheet" | "text" | "markdown" | "json" | "jsonl" | "code" | "weblink";

export type SourceStatus = "queued" | "analyzing" | "ready" | "ready_partial" | "failed";

/**
 * Emitted on `source://status` (docs/02 §5).
 */
export type SourceStatusEvent = { projectId: string, sourceId: string, status: SourceStatus, errorCode: string | null, };

/**
 * `stream://citations` payload.
 */
export type StreamCitations = { streamId: string, messageId: string, citations: Citation[], };

/**
 * `stream://delta` payload (docs/02 §5).
 */
export type StreamDelta = { streamId: string, 
/**
 * "text" | "reasoning"
 */
kind: string, text: string, };

/**
 * `stream://done` payload.
 */
export type StreamDone = { streamId: string, cancelled: boolean, truncated: boolean, usage: TokenUsage | null, };

/**
 * `stream://error` payload.
 */
export type StreamError = { streamId: string, error: AppError, };

export type StudioSendInput = { projectId: string, tabId: string, text: string, 
/**
 * `"project"` or `"source:<id>"`.
 */
scope: string, };

/**
 * Returned by `studio_send` / `studio_resolve_tool`. The frontend refetches
 * tabs + artifacts on success; this is the loop's own summary of what happened.
 */
export type StudioSendResult = { 
/**
 * How many model round-trips the loop ran (0..=10).
 */
iterations: number, 
/**
 * The loop stopped at the 10-iteration cap with tool calls still pending —
 * the frontend shows a "続行" button (AC-6-8).
 */
needsContinue: boolean, 
/**
 * A `write_file` call is waiting for the reader's approval (AC-6-5 card).
 */
awaitingApproval: boolean, 
/**
 * The reader cancelled mid-loop (`studio_cancel`).
 */
cancelled: boolean, 
/**
 * Convenience: how many context messages were folded into a summary this
 * turn (AC-6-9). 0 when nothing was trimmed.
 */
summarisedMessages: number, };

export type StudioTab = { id: string, threadId: string, title: string, ordinal: number, 
/**
 * `"project"` or `"source:<id>"` (docs/06 §6 scope selector).
 */
scope: string, messages: Array<ChatMessage>, };

export type TestResult = { ok: boolean, models: Array<string>, latencyMs: number, supportsVision: boolean, supportsTools: boolean, supportsEmbed: boolean, jsonSchema: boolean, note: string | null, };

export type TextToMarkdownInput = { text: string, };

export type Thread = { id: string, scope: string, sourceId: string | null, locatorKey: string | null, title: string, messages: Array<ChatMessage>, };

export type TokenUsage = { promptTokens: number, completionTokens: number, };

/**
 * One line of a transcript. `start` / `end` are seconds from the top of the
 * media (AC-5-3, AC-5-8).
 */
export type TranscriptSegment = { start: number, end: number, text: string, };

export type Transcription = { 
/**
 * "base" | "small" | "medium" | "large-v2"
 */
whisperModel: string, 
/**
 * "auto" | ISO code
 */
language: string, hardwareAccel: boolean, };

export type UpdateProjectInput = { id: string, name: string | null, description: string | null, color: ProjectColor | null, };

export type VersionVerdict = "accept" | "migrate" | "warnOpen" | "reject";

export type ViewerTab = { id: string, sourceId: string, kind: SourceKind, name: string, locator: unknown, pinned: boolean, ordinal: number, };

export type WhisperModel = { 
/**
 * `"base" | "small" | "medium" | "large-v2"`.
 */
name: string, 
/**
 * Rough download size, for the pre-flight disk check (AC-5-2).
 */
approxBytes: number, downloaded: boolean, 
/**
 * SHA-256 of the downloaded file, recorded after the first successful
 * download (DECISIONS D-15 — no authoritative upstream manifest to pin to).
 */
sha256: string | null, 
/**
 * Absolute path once downloaded.
 */
path: string | null, 
/**
 * True for the model currently bound in settings.
 */
selected: boolean, };

export type WrittenFile = { path: string, };
