// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddFilesInput = { projectId: string, paths: Array<string>, };

export type AppError = { code: string, message: string, i18nKey: string, details: unknown | null, retriable: boolean, };

export type AppInfo = { version: string, buildDate: string, dataDir: string, license: string, };

export type CreateProjectInput = { name: string, description: string | null, color: ProjectColor | null, };

/**
 * A page / slide / segment / sheet / section — the citation unit (docs/03 §2 GLOSSARY).
 * Returned by `source_get_document` (wired in Phase 2).
 */
export type DocumentUnit = { id: string, sourceId: string, ordinal: number, kind: string, title: string | null, text: string, imageRel: string | null, locator: unknown, };

export type Job = { id: string, kind: JobKind, status: JobStatus, projectId: string | null, sourceId: string | null, phase: string | null, done: number, total: number, message: string | null, startedAt: string | null, endedAt: string | null, };

export type JobKind = "ingest" | "transcribe" | "embed" | "export" | "import";

/**
 * Payload of the `job://progress` event (docs/02 §5).
 */
export type JobProgress = { jobId: string, projectId: string | null, sourceId: string | null, kind: JobKind, phase: string, done: number, total: number, message: string | null, };

export type JobStatus = "queued" | "running" | "done" | "failed" | "cancelled";

export type Project = { id: string, name: string, description: string, color: ProjectColor, schemaVersion: string, createdAt: string, updatedAt: string, openedAt: string | null, archivedAt: string | null, sortOrder: number, };

/**
 * A stable colour slot for project cards (resolved to a token on the frontend).
 * Consumed by the projects service in Phase 1.
 */
export type ProjectColor = "accent-1" | "accent-2" | "accent-3" | "accent-4" | "accent-5";

/**
 * Lighter row for the home grid / sidebar (adds counts).
 */
export type ProjectSummary = { id: string, name: string, description: string, color: ProjectColor, archived: boolean, sourceCount: number, lastOpenedAt: string | null, updatedAt: string, };

export type Source = { id: string, kind: SourceKind, originalName: string, url: string | null, mime: string | null, bytes: number, sha256: string | null, status: SourceStatus, errorCode: string | null, errorMessage: string | null, lang: string | null, pageCount: number | null, durationMs: number | null, summary: string | null, addedAt: string, analyzedAt: string | null, };

export type SourceKind = "pdf" | "slides" | "doc" | "image" | "audio" | "video" | "sheet" | "text" | "markdown" | "json" | "jsonl" | "code" | "weblink";

export type SourceStatus = "queued" | "analyzing" | "ready" | "ready_partial" | "failed";

/**
 * Emitted on `source://status` (docs/02 §5).
 */
export type SourceStatusEvent = { projectId: string, sourceId: string, status: SourceStatus, errorCode: string | null, };

export type UpdateProjectInput = { id: string, name: string | null, description: string | null, color: ProjectColor | null, };
