// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { code: string, message: string, i18nKey: string, details: unknown | null, retriable: boolean, };

export type AppInfo = { version: string, buildDate: string, dataDir: string, license: string, };

export type Job = { id: string, kind: JobKind, status: JobStatus, projectId: string | null, sourceId: string | null, phase: string | null, done: number, total: number, message: string | null, startedAt: string | null, endedAt: string | null, };

export type JobKind = "ingest" | "transcribe" | "embed" | "export" | "import";

/**
 * Payload of the `job://progress` event (docs/02 §5).
 */
export type JobProgress = { jobId: string, projectId: string | null, sourceId: string | null, kind: JobKind, phase: string, done: number, total: number, message: string | null, };

export type JobStatus = "queued" | "running" | "done" | "failed" | "cancelled";

/**
 * A stable colour slot for project cards (resolved to a token on the frontend).
 * Consumed by the projects service in Phase 1.
 */
export type ProjectColor = "accent-1" | "accent-2" | "accent-3" | "accent-4" | "accent-5";
